language: python
python:
    - "3.4"
install:
    - pip install tox
script:
    - tox

before_deploy: "pip install wheel --upgrade"
deploy:
    provider: pypi
    user: "jelford"
    password: ${PYPI_PASSWORD}
    on:
        tags: true
        branch: master
        distributions: "sdist bdist_wheel"
after_deploy:
    "python setup.py bdist_wheel"
    "twine upload -u jelford -p ${PYPI_PASSWORD} dist/*.whl"
