language: python
python:
    - "3.4"
install:
    - pip install tox
script:
    - tox

deploy:
    provider: pypi
    user: "jelford"
    password: ${PYPI_PASSWORD}
    on:
        tags: true
        branch: master
        distributions: "sdist bdist_wheel"
